import typing

@typing.overload
def str2bool(value: str, raise_exc: typing.Literal[False] = False) -> bool | None: ...
@typing.overload
def str2bool(value: str, raise_exc: typing.Literal[True]) -> bool: ...
def str2bool(value: str, raise_exc: bool = False) -> bool | None: ...
def str2bool_exc(value: str) -> bool: ...
